// app/layout.js

import Navbar from './components/Navbar'
import './globals.css'
import ReduxProvider from './providers/ReduxProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
        <Navbar />
        {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
